### PR TITLE
Implement key movement through keyboard/controller

### PR DESCRIPTION
**Pull request by rsubtil**
https://user-images.githubusercontent.com/6501975/218139995-b8f5cdc8-9cc0-4241-aa1f-af95c763d7e2.mp4

This allows users to use keyboard and controllers to navigate the virtual keys and input text. Since only one element can be "focused" at a time in Godot, I've added another internal focused variable and manually draw the buttons to achieve the same effect.

### CODE REVIEW

**Comment by moritz-t-w** [comment]
@martinfuchs bump

**Comment by rsubtil** [comment]
The repo was updated for Godot 4, so this PR is no longer relevant. For Godot 4, a simpler way to achieve this is to refactor the keyboard object to become a `Window`/`Popup`, allowing it to have it's own focused objects, separate from the main game.

@martinfuchs if you want, I can still leave this PR open to target the `godot-3.5` branch instead.

**Comment by moritz-t-w** [comment]
That's what I was thinking

**Comment by moritz-t-w** [comment]
> The repo was updated for Godot 4

yeah that was me

**Comment by rsubtil** [comment]
Since it seems development is focused for Godot 4, and I no longer have a Godot 3 project using this, I think it's best to close it.

**Comment by NBumgardner** [comment]
Nice video attachment, this closed PR looks like just the behavior I am looking for to allow controllers/gamepads to use LineEdit nodes! I have some experience migrating from Godot 3 to Godot 4 so I will see if I can get it working without the mentioned `Window`/`Popup` refactor.

**Pull request closed without merging**
